spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://ace:ace@clusterhelpdesk.xemb2gp.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true
